version: '3.9'
services:
  db: 
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports: 
      - "${DB_PORT}:5432"
    networks:
      - custom 
  db_test: 
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
    ports: 
      - "${DB_PORT_TEST}:5432"
    networks:
      - custom 
networks:
  custom: 
    driver: bridge